### ISSUE TITLE
first layer calibration - wrong temperature

### ISSUE THREAD

**Issue by keksa** [prusa3d/Prusa-Firmware-Buddy#280]
FW 4.0.4

The in-built first layer calibration tool is doing mesh bed leveling with nozzle temperature of 215 °C. Since regular prints do mesh bed leveling with nozzle temperature of 170 °C and then wait up for higher temp, I think this might be a bug. 

This also results in random blobs of filament on the bed before the calibration actually starts.

**Comment by Isaac12x** [comment]
I think this one is solved with the 4.0.5 update. Can you check?

**Comment by keksa** [comment]
Hello @Isaac12x, just updated to 4.0.5 and checked. Nothing changed, still the same behaviour.

**Comment by JohnnyDeer** [comment]
Hi @keksa , thank you for reporting, but this issue is already reported. I'm closing this one as duplicate of #157
