### ISSUE TITLE
[BUG] Error! #13604 when MK4 powered on

### ISSUE THREAD

**Issue by dp250f** [prusa3d/Prusa-Firmware-Buddy#3597]
**Printer type** - MK4

**Printer firmware version** - 5.1.2 release and newer

**Original or Custom firmware** - Custom (#define HEATER_0_MAXTEMP 320)

**Optional upgrades** - Micro Swiss CM2 RepRap V5-V6 0.4mm nozzle, silicone hot end sock

**USB drive or USB/Octoprint**
  PrusaConnect

**Describe the bug**
  Error! #13604 displays when powered on.
  Printer boots normally when reset with reset button.

**How to reproduce**
  Flash firmware. Turn off printer. Turn it back on.

**Expected behavior**
  Printer should boot normally

**G-code**
  N/A

**Crash dump file**
  "No crash dump to save"

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by bkerler** [comment]
Haven't tested the 5.1.2 yet, but Error #13604 means : "Firmware file missing in the USB flash!". It could be that the file wasn't written completely or the filesystem could be broken. Also make sure you don't have several fw upgrades in the same root directory on the usb stick.

**Comment by bkerler** [comment]
Version 5.1.2 says that this issue should be fixed ... so maybe this version introduced an issue instead.

**Comment by dp250f** [comment]
Reformatted the USB drive. Still displays error on cold boot and not on reset.
I also tried without the USB drive and it boots normally.

Other than the error message on cold boot, everything works normally.

**Comment by dp250f** [comment]
Bought a new flash drive, formatted FAT32. Still the same thing happening.

**Comment by dp250f** [comment]
Built and flashed 6.0.0 release today. Issue persists.
