### ISSUE TITLE
[BUG] [MK3.5] Board temperature missing - "Not initialized"

### ISSUE THREAD

**Issue by arekm** [prusa3d/Prusa-Firmware-Buddy#3745]
**Printer type** - MK3.5
**Printer firmware version** - 5.2.0
**Original or Custom firmware** - Original

**Describe the bug**
Buddy board temperature is not shown.

**How to reproduce**
Go to "Sensor info" menu and notice there is "Not initialized" instead of board temperature.

![mk3 5-board-temp](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/50869/d45669b3-9b1e-4715-8980-bc74e686b508)

**Expected behavior**
Board temperature shown, just like on MK4 firmware.

**Comment by bkerler** [comment]
Indeed. Looks like the code for the board temp wasn't added for an unknown reason. Here's the PR #3749 that fixes this issue.

**Comment by CZDanol** [comment]
Internal ticket number: BFW-5074

**Comment by CZDanol** [comment]
Fix merged :) Should got into the next release.

**Comment by magistersmax** [comment]
I updated to 5.2.1 today and the board temperature is still showing as Not Initialized.  

![MK3 5 5 2 1 Board Temp 1](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/36339949/03f0b1e5-e85e-4051-9910-183b1be276ff)
![MK3 5 5 2 1 Board Temp 2](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/36339949/221d8dcb-ad30-4a5b-878e-ae94800f26ed)

**Comment by arekm** [comment]
Same here on 5.2.1.

**Comment by bkerler** [comment]
People, just because it's merged doesn't mean it's already in the next release. Relax.

**Comment by arekm** [comment]
Well, it was mentioned in 5.2.1 announcement as fixed.

**Comment by bkerler** [comment]
Indeed, I just checked and although the bugfix is mentioned in the v5.2.1 release notes, the PR isn't included in the commits @JohnnyDeer @CZDanol.

**Comment by CZDanol** [comment]
Yep, it was supposed to go there. Sorry, guys, looks like administrative error. I've notified the team about that.

**Comment by bkerler** [comment]
Thanks @CZDanol

**Comment by HonzaJaros** [comment]
Sorry for writing here, but this exactly is happening in MK4 fw 5.1.3.
![IMG_4952](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/19324824/c90530e0-52dc-443c-a5c6-7d1af93edc88)
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/19324824/500ebac2-ce30-455c-b65d-b67d692fb970)
