### ISSUE TITLE
[BUG] MMU3 Filament load does not reach Finda -- times out

### ISSUE THREAD

**Issue by jsrumsey** [prusa3d/Prusa-Firmware-Buddy#4097]
### Printer model

MK3.5 with MMU3

### Firmware version

6.0.4

### Upgrades and modifications

None

### Printing from...

Prusa Connect or direct start print at the printer.

### Describe the bug

When attempting to first load filament to MMU, it doesn't travel far enough to reach the Finda before it stops travel and asks for retry, which then rehomes the MMU, smashing the partially exposed filament in the MMU.

### Expected behavior

It should detect filament at Finda, and then continue to load to the extruder.

**Comment by jsrumsey** [comment]
This appears to have been resolved by cleaning out old printer configs and creating a fresh one.

**Comment by sven94-collab** [comment]
how do you clean out old printer configs and create a fresh one.  i am still getting this issue over a year after this fix
